### ISSUE TITLE
Had to change env in python file to python2

### ISSUE THREAD

**Issue by z1lt0id** [gsingh93/archutil#2]
Was getting a syntax error due to it not point python2 - was pointing to python3.  Changed env in python file to resolve issue.

**Comment by gsingh93** [comment]
I had `python` pointing to `python2` on my Arch install, so I had completely forgot to do that in the shebang. I've made this change so it should definitely work on Arch now, and any newer debian distro.

That being said, I know older Debian based distributions don't have `python2`, and I don't know anything about distributions that are Debian or Arch. I guess I'll just handle those cases as people report them.

Thanks for the bug report!
