### ISSUE TITLE
Add to AUR

### ISSUE THREAD

**Issue by razor-x** [gsingh93/archutil#3]
I've been looking for a tool like this. Would you consider adding it as an AUR package?

You might want to publish it to PyPI first and take the sources from there (or release and tag versions on GitHub).

**Comment by gsingh93** [comment]
I'll publish it to the AUR soon, I'm a bit busy right now. I maintain another package that pulls from Git in the AUR, I'll just do the same for this.

**Comment by gsingh93** [comment]
I've uploaded the package here: https://aur.archlinux.org/packages/archutil/

Note that since this is now installed globally, it checks for a config.py file in `~/.config/archutil/config.py` as well.
